spring:
  application:
    name: fintrack-backend

  datasource:
    url: jdbc:mysql://thomas.proxy.rlwy.net:45025/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: OGVwneHsovArSDiTpmGLIDVSgQUBCTpt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

fintrack:
  security:
    jwt:
      secret: dGhlLXByZW1pdW0tcHJvZHVjdGlvbi1yZWFkeS1maW50cmFjay1wcm8tc2VjdXJpdHktamt0LXNlY3JldC1rZXktdmFsdWUtMjAyNg==
      expiration-ms: 86400000